upconsulting/IsisCB

- isiscb/isiscb/production_settings.py
- isiscb/isisdata/elasticsearch_backend.py
- isiscb/isisdata/forms.py
- isiscb/isisdata/models.py
- isiscb/isisdata/search_indexes.py
- isiscb/isisdata/templates/search/indexes/isisdata/citation_text.txt
- isiscb/isisdata/templatetags/metadata_filters.py
- isiscb/isisdata/urls.py
- isiscb/isisdata/utils.py
- requirements.txt
Major refactor of ``CitationIndex``. This also switches us away from the elasticstack backend, in favor of our own custom backend based on the vanilla django-haystack ElasticSearch backend. Finally, we're using a custom variant of django-haystack that supports more efficient indexing.
Also delivers: 
* ISISCB-127 Add the ability to use wildcards in the search
* ISISCB-411 Book review titles not included in main search document
> Search optimization

- isiscb/curation/filters.py
- isiscb/curation/templates/curation/bulk_select_citation.html
- isiscb/curation/templates/curation/citation_change_view.html
- isiscb/curation/templates/curation/citation_list_view.html
- isiscb/curation/templates/curation/list_view.html
- isiscb/curation/views.py
@erickpeirson how about using POST for the filters coupled with the session? This way the bulk select is simply a filter and it works nicely with pagination. 
(the page parameter still needs to be reset for a new search)
> try using post for filters

- isiscb/curation/templates/curation/fragment_citation_tracking.html
- isiscb/curation/tracking.py
- isiscb/curation/views.py
still needs permission checks;
> [ISISCB-775] added buttons for adding tracking in citations

- isiscb/curation/templates/curation/citation_acrelation_changeview.html
- isiscb/curation/views.py
and added “load more” button to load more than 10 authority results in ACR view.
> [ISISCB-837] added exact matches to authority result list

- isiscb/curation/filters.py
- isiscb/curation/views.py
- isiscb/isisdata/models.py
- isiscb/isisdata/views.py
- isiscb/zotero/test_data/TestBirthDeathDates.rdf
Fixes  ISISCB-854 and ISISCB-855
> Search query normalization in curation and user interface

- isiscb/curation/filters.py
- isiscb/curation/forms.py
- isiscb/curation/rules.py
- isiscb/curation/templates/curation/authority_change_view.html
- isiscb/curation/templates/curation/citation_change_view.html
- isiscb/curation/templatetags/permission_tags.py
- isiscb/curation/views.py
- isiscb/isisdata/migrations/0052_auto_20170205_2120.py
- isiscb/isisdata/migrations/0053_auto_20170205_2125.py
- isiscb/isisdata/migrations/0054_auto_20170205_2248.py
- isiscb/isisdata/models.py
fixed dataset filter for authorities; added dataset field to authority view; added indexes for classification fields
> [ISISCB-860] added ‘no dataset’ rule

- isiscb/zotero/templates/zotero/retrieve_accession.html
> reduced height of search results in zotero authority resolution

- isiscb/zotero/ingest.py
- isiscb/zotero/models.py
- isiscb/zotero/templates/zotero/retrieve_accession.html
- isiscb/zotero/views.py
* [ISISCB-1048] fixes and issue with ISBNs/DOIs and additional URIs
still to find out: can there be ISBN and DOI given?
* [ISISCB-1048] link production citations if available
otherwise create new citation
* [ISISCB-1048] show resolved citations on ingest page
> Bug/isiscb 1048 (#411)

- isiscb/curation/templates/curation/authority_linkeddata_duplicates.html
- isiscb/curation/templates/curation/fragment_authority_linkeddata.html
- isiscb/curation/templates/curation/fragment_citation_linkeddata.html
- isiscb/curation/templates/curation/fragment_linkeddata_duplicates.html
- isiscb/curation/urls.py
- isiscb/curation/views.py
for deleting duplicate linkeddata entries
> [ISISCB-1038] added delete duplicates button to authorities

- isiscb/curation/templates/curation/authority_acrelations.html
- isiscb/curation/templates/curation/fragment_authority_acrelations.html
- isiscb/curation/urls.py
- isiscb/curation/views.py
still missing: after removal, total number needs to be updated.
> [ISISCB-1052] lazy load acrelations

- isiscb/isisdata/export_authority.py
renamed related authorities to related citations
> [ISISCB-1037] change attribute field names, added start/end

- isiscb/curation/forms.py
- isiscb/curation/templates/curation/citations_export.html
- isiscb/curation/views.py
- isiscb/isisdata/tasks.py
* [ISISCB-1066] added checkbox to export (or not) linked records
* [ISISCB-1066] fixed typo
> Story/isiscb 1066 (#449)

- isiscb/curation/taskslib/authority_tasks.py
and added prefix to fields that can hold either authorities or citations
> [ISISCB-1145] added linked data subject to allowed fields

- isiscb/curation/templates/curation/fragment_citation_tracking.html
- isiscb/isisdata/export.py
- isiscb/isisdata/tests/test_export.py
* [ISISCB-1156] show creator and creation date
* [ISISCB-1156] export tracking id; adjust display for empty values
* [ISISCB-1156] fix test cases
* [ISISCB-1156] revert test settings
> Story/isiscb 1156 (#540)

- isiscb/curation/templates/curation/authority_create_view.html
- isiscb/curation/views.py
- isiscb/zotero/templates/zotero/retrieve_accession.html
- isiscb/zotero/views.py
> [ISISCB-1168] create authorities through authority create page

- isiscb/curation/templates/curation/authority_create_view.html
- isiscb/curation/templatetags/render_object.py
- isiscb/curation/views.py
- isiscb/zotero/ingest.py
- isiscb/zotero/templates/zotero/retrieve_accession.html
- isiscb/zotero/templates/zotero/show_citation_matches.html
- isiscb/zotero/templatetags/zotero_tags.py
- isiscb/zotero/tests.py
- isiscb/zotero/urls.py
- isiscb/zotero/views.py
* [ISISCB-1163] first changes to resolved authority list
* [ISISCB-1163] fixed 1. and 2.
* [ISISCB-1163] match title, type, and journal when searching for matches
* [ISISCB-1163] fixed some feedback points
* [ISISCB-1163] show only three matches by title
* [ISISCB-1163] show authors for matching citations
* [ISISCB-1163] worked on items 4-6. of ticket
* [ISISCB-1163] edits according to comments
* [ISISCB-1163] fixed test cases
> Story/isiscb 1163 (#562)

- isiscb/curation/static/curation/css/curation.css
- isiscb/curation/templates/curation/fragment_citation_categories_subjects.html
- isiscb/curation/templates/curation/fragment_citation_fields.html
and added indicators for status
> [IEXP-55] added all ccrel to citation curation view

- isiscb/curation/templates/curation/authority_attribute_changeview.html
- isiscb/curation/templates/curation/fragment_authority_attributes.html
- isiscb/curation/templates/curation/fragment_authority_header.html
- isiscb/curation/templates/curation/list_view.html
- isiscb/curation/views.py
- isiscb/isisdata/filters.py
* [IEXP-281] added citation filter for linked authority; fixed pagin. bug for authorities
* [IEXP-280] added warning about citation reindexing for geocodes
[IEXP-281]: https://upconsulting.atlassian.net/browse/IEXP-281
[IEXP-280]: https://upconsulting.atlassian.net/browse/IEXP-280
> Story/iexp 281 (#675)

- isiscb/curation/authority_views/relation_views.py
- isiscb/curation/forms.py
- isiscb/curation/templates/curation/authority_aarelation_changeview.html
- isiscb/curation/templates/curation/authority_aarelation_delete.html
- isiscb/curation/templates/curation/authority_aarelations.html
- isiscb/curation/templates/curation/authority_change_view.html
- isiscb/curation/templates/curation/authority_search_dropdown.js
- isiscb/curation/templates/curation/fragment_authority_aarelations.html
- isiscb/curation/templatetags/permission_tags.py
- isiscb/curation/urls.py
- isiscb/curation/views.py
- isiscb/isisdata/models.py
* [IEXP-283] started on aarelation view
* [IEXP-283] aacreation works now, but swapping in aarelation form is broken
* [IEXP-283] fixed aarelation views/functions
* [IEXP-283] fixed label CCR to AAR
[IEXP-283]: https://upconsulting.atlassian.net/browse/IEXP-283
[IEXP-283]: https://upconsulting.atlassian.net/browse/IEXP-283
[IEXP-283]: https://upconsulting.atlassian.net/browse/IEXP-283
[IEXP-283]: https://upconsulting.atlassian.net/browse/IEXP-283
> Story/iexp 283 (#690)

- isiscb/isisdata/views.py
* [IEXP-322] authority page revamp with wikipedia info
* [IEXP-322] switched wikipedia api calls to https and added font awesome cd with updated version
* [IEXP-324] citation page revamp v1
* [IEXP-324] citation page revamp with images fetched from google books
* [IEXP-322] authority page touchups, changed related authorities display; changed wikipedia fetch to exclude periodical and authors/contribs
* citation page revamp with featured images and related citations list
* [story/IEXP-324] citation page touchups
* [story/IEXP-322] fixed bad if logic from my broken mind
* story/IEXP-324 citation page bug fixes
* [story/IEXP-324] added comments and changed citation type checks to using controlled names instead of display names
* [story/IEXP-322] moving wikipedia image fetching for authority …
> Story/iexp 331 (#756)
